name: Angular DevOps CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    name: Test Angular Application
    runs-on: [self-hosted, devops-lab]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --watch=false
