name: CD Production

on:
  workflow_run:
    workflows: ["CD QA Angular"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy-production:
    name: Deploy Production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, devops-lab]
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Show environment test
        run: echo "Deploying to ${{ vars.APP_ENV  }}"

      - name: Find approved artifact
        id: find-artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.event.workflow_run.id }}
          REPO: ${{ github.repository }}
        run: |
          ARTIFACT_NAME=$(gh api \
            repos/$REPO/actions/runs/$RUN_ID/artifacts \
            --jq '.artifacts[] | select(.name | startswith("angular-build-approved-")) | .name' \
            | head -n 1)

          if [ -z "$ARTIFACT_NAME" ]; then
            echo "No se encontró el artifact aprobado."
            exit 1
          fi

          echo "Artifact encontrado: $ARTIFACT_NAME"
          echo "artifact_name=$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"

      - name: Download approved Angular build
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.find-artifact.outputs.artifact_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: dist/angular-devops-lab

      - name: Verify downloaded artifact
        run: |
          echo "Contenido descargado para producción:"
          find dist/angular-devops-lab -maxdepth 2 -type f
#          echo "Metadata de deployment:"
#          cat dist/angular-devops-lab/deployment-info.txt || true

      - name: Build Docker image
        run: docker build -t angular-devops-lab:1.0 .

      - name: Deploy with Docker Compose
        run: docker compose up -d

      - name: Debug Docker
        run: |
          echo "=== Docker containers ==="
          docker ps -a

          echo "=== Docker ports ==="
          docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

      - name: Docker logs
        run: docker logs angular-devops-lab

      - name: Health check
        run: curl -f http://127.0.0.1:80
