name: CD QA Angular
on:
  workflow_run:
    workflows: ["CI DevOps Angular"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy-qa:
    name: Deploy QA
    if: ${{ github.event.workflow_run.conclusion == 'success'  }}
    runs-on: [self-hosted, devops-lab]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download Angular build
        uses: actions/download-artifact@v4
        with:
          name: angular-build-${{ github.event.workflow_run.head_sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: dist/angular-devops-lab

      - name: Verify downloaded artifact
        run: |
          echo "Contenido descargado:"
          find dist/angular-devops-lab -maxdepth 2 -type f

#      - name: Create deployment metadata
#        run: |
#          echo "COMMIT_SHA=${{ github.event.workflow_run.head_sha }}" > deployment-info.txt
#          echo "CI_RUN_ID=${{ github.event.workflow_run.id }}" >> deployment-info.txt
#          echo "QA_RUN_ID=${{ github.run_id }}" >> deployment-info.txt
#          echo "ARTIFACT_NAME=angular-build-approved-${{ github.event.workflow_run.head_sha }}" >> deployment-info.txt

      - name: Upload approved Angular build
        uses: actions/upload-artifact@v4
        with:
          name: angular-build-approved-${{ github.event.workflow_run.head_sha }}
          path: dist/angular-devops-lab
 #               deployment-info.txt
          retention-days: 7

      - name: Build Docker image
        run: docker build -t angular-devops-lab:1.0 .

      - name: Deploy with Docker Compose
        run: docker compose up -d

      - name: Debug Docker
        run: |
          echo "=== Docker containers ==="
          docker ps -a

          echo "=== Docker ports ==="
          docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

      - name: Docker logs
        run: docker logs angular-devops-lab

      - name: Health check
        run: curl -f http://127.0.0.1:80
